version: '3.1'
#
services:

  base: 
    build: bacula-base/
    image: fametec/bacula-base:9.6.3
#    
  db:
    build: bacula-catalog/
    image: fametec/bacula-catalog:9.6.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    # volumes:
    #   - pgdata:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
#
  bacula-standalone:
    build: bacula-standalone/
    image: fametec/bacula-standalone:9.6.3
    restart: unless-stopped
    volumes:
      - ./etc:/opt/bacula/etc:ro
    depends_on: 
      - db      
    ports:
      - 9101:9101
      - 9102:9102
      - 9103:9103
#
  baculum:
    build: baculum/
    image: fametec/baculum:9.6.3
    restart: unless-stopped
    depends_on: 
      - db
      - bacula-standalone
    volumes:
      - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - ./etc/baculum:/etc/baculum:rw
    ports:
      - 9095:9095
      - 9096:9096
# 
#volumes: 
#  pgdata:
